# ToiUuPC-Bundled.ps1 - PMK Toolbox v3.3.2-final (Bundled - one-file remote)
# Run: irm https://raw.githubusercontent.com/mkhai2589/toiuupc/main/ToiUuPC-Bundled.ps1 | iex
# Author: Minh Khải (PMK) - https://www.facebook.com/khaiitcntt
# This file is auto-generated by Compile.ps1 - DO NOT edit directly

[CmdletBinding()]
param([switch]$Silent)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
Clear-Host

# Optional console size
try {
    $Host.UI.RawUI.BufferSize = New-Object Management.Automation.Host.Size(100, 50)
    $Host.UI.RawUI.WindowSize = New-Object Management.Automation.Host.Size(100, 50)
} catch {}

# Admin check & relaunch
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "Yêu cầu chạy với quyền Administrator!" -ForegroundColor Red
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

$ProgressPreference = 'SilentlyContinue'

# ────────────────────────────────────────────────────────────────
# Nội dung các function được gộp từ folder functions
# (Bạn có thể paste toàn bộ nội dung các file functions vào đây theo thứ tự)
# ────────────────────────────────────────────────────────────────

# === Show-PMKLogo.ps1 ===
function Show-PMKLogo {
    $logo = @"
╔══════════════════════════════════════════════════════════════════════════╗
║ ██████╗ ███╗   ███╗██╗  ██╗      ████████╗ ██████╗  ██████╗ ██╗          ║
║ ██╔══██╗████╗ ████║██║ ██╔╝      ╚══██╔══╝██╔═══██╗██╔═══██╗██║          ║
║ ██████╔╝██╔████╔██║█████╔╝          ██║   ██║   ██║██║   ██║██║          ║
║ ██╔═══╝ ██║╚██╔╝██║██╔═██╗          ██║   ██║   ██║██║   ██║██║          ║
║ ██║     ██║ ╚═╝ ██║██║  ██╗         ██║   ╚██████╔╝╚██████╔╝███████╗     ║
║ ╚═╝     ╚═╝     ╚═╝╚═╝  ╚═╝         ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝     ║
║                 PMK Toolbox - Tối ưu Windows                             ║
╚══════════════════════════════════════════════════════════════════════════╝
"@
    Write-Host $logo -ForegroundColor Cyan   # hoặc $HEADER_COLOR nếu đã define
}

# === utils.ps1 ===
$global:TEXT_COLOR     = "White"
$global:HEADER_COLOR   = "White"
$global:SUCCESS_COLOR  = "Green"
$global:ERROR_COLOR    = "Red"
$global:BORDER_COLOR   = "DarkGray"
$global:WARNING_COLOR  = "Yellow"

function Reset-ConsoleStyle {
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = $TEXT_COLOR
    Clear-Host
}

function Show-SystemHeader {
    $os = Get-CimInstance Win32_OperatingSystem
    $cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
    $ram = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
    $build = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId

    Write-Host "==================================================================================" -ForegroundColor $BORDER_COLOR
    Write-Host "PMK TOOLBOX v3.3.2" -ForegroundColor $HEADER_COLOR
    Write-Host "User: $($env:USERNAME) | PC: $($env:COMPUTERNAME) | OS: $($os.Caption) Build $build" -ForegroundColor $TEXT_COLOR
    Write-Host "CPU: $($cpu.Name.Split('@')[0].Trim()) | RAM: $ram GB" -ForegroundColor $TEXT_COLOR
    Write-Host "Author: Minh Khải (PMK) - https://www.facebook.com/khaiitcntt" -ForegroundColor $HEADER_COLOR
    Write-Host "==================================================================================" -ForegroundColor $BORDER_COLOR
    Write-Host ""
}

function Set-RegistryTweak {
    param (
        [string]$Path,
        [string]$Name,
        [object]$Value,
        [string]$Type = "DWord",
        [switch]$CreatePath
    )
    try {
        if ($CreatePath -and -not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
    } catch {
        Write-Warning "Failed registry: $Path\$Name = $Value → $_"
    }
}

# Create-RestorePoint, Remove-WindowsApp, ... (paste đầy đủ nội dung utils.ps1 còn lại vào đây)

# === install-apps.ps1, tweaks.ps1, dns-management.ps1, clean-system.ps1 ===
# ────────────────────────────────────────────────────────────────
# Paste toàn bộ code còn lại của 4 file này vào đây (theo thứ tự bạn muốn load)
# Ví dụ:
# function Install-AppsQuick { ... }
# function Invoke-TweaksMenu { ... }
# function Set-DNSServerMenu { ... }
# function Invoke-CleanSystem { ... }
# ────────────────────────────────────────────────────────────────

# (Bạn cần copy nội dung thực tế từ các file functions của bạn và paste vào phần này)
# Nếu chưa có thời gian paste hết, tạm thời để trống và chạy Compile.ps1 local để sinh bundled tự động

# ────────────────────────────────────────────────────────────────
# Menu chính (giống ToiUuPC.ps1)
# ────────────────────────────────────────────────────────────────
do {
    Reset-ConsoleStyle
    Show-PMKLogo
    Show-SystemHeader

    Write-Host "MENU CHÍNH - PMK TOOLBOX (Bundled Mode)" -ForegroundColor $HEADER_COLOR
    Write-Host "======================================" -ForegroundColor $BORDER_COLOR
    Write-Host ""

    Write-Host " [1] Cài đặt ứng dụng nhanh" -ForegroundColor $HEADER_COLOR
    Write-Host " [2] Vô hiệu hóa Telemetry & Tweaks" -ForegroundColor $HEADER_COLOR
    Write-Host " [3] Dọn dẹp file tạm & hệ thống" -ForegroundColor $HEADER_COLOR
    Write-Host " [4] Quản lý DNS & mạng" -ForegroundColor $HEADER_COLOR
    Write-Host " [5] Thoát" -ForegroundColor $HEADER_COLOR

    Write-Host ""
    Write-Host "Nhập số lựa chọn (1-5) hoặc ESC để thoát: " -NoNewline -ForegroundColor $HEADER_COLOR

    $input = Read-Host

    if ([Console]::KeyAvailable) {
        $key = [Console]::ReadKey($true)
        if ($key.Key -eq [ConsoleKey]::Escape) { Write-Host "`nThoát..."; exit }
    }

    switch ($input) {
        "1" { Install-AppsQuick }
        "2" { Invoke-TweaksMenu }
        "3" { Invoke-CleanSystem }
        "4" { Set-DNSServerMenu }
        "5" { Write