# ToiUuPC-Bundled.ps1 - PMK Toolbox v3.3.2-final (Bundled - All-in-One)
# Run: irm https://raw.githubusercontent.com/mkhai2589/toiuupc/main/ToiUuPC-Bundled.ps1 | iex
# Author: Minh Khải (PMK) - https://www.facebook.com/khaiitcntt
# Generated by Compile.ps1 - DO NOT edit directly

[CmdletBinding()]
param([switch]$Silent)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
Clear-Host

# Optional console size
try {
    $Host.UI.RawUI.BufferSize = New-Object Management.Automation.Host.Size(100, 50)
    $Host.UI.RawUI.WindowSize = New-Object Management.Automation.Host.Size(100, 50)
} catch {}

# Admin check & relaunch
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "Yêu cầu chạy với quyền Administrator!" -ForegroundColor Red
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

$ProgressPreference = 'SilentlyContinue'

# ────────────────────────────────────────────────────────────────
# COLOR PALETTE
# ────────────────────────────────────────────────────────────────
$global:TEXT_COLOR     = "White"
$global:HEADER_COLOR   = "Cyan"
$global:SUCCESS_COLOR  = "Green"
$global:ERROR_COLOR    = "Red"
$global:BORDER_COLOR   = "DarkGray"
$global:WARNING_COLOR  = "Yellow"

# ────────────────────────────────────────────────────────────────
# FUNCTIONS (gộp từ tất cả file trong functions/)
# ────────────────────────────────────────────────────────────────

# Show-PMKLogo
function Show-PMKLogo {
    $logo = @"
╔══════════════════════════════════════════════════════════════════════════╗
║ ██████╗ ███╗   ███╗██╗  ██╗      ████████╗ ██████╗  ██████╗ ██╗          ║
║ ██╔══██╗████╗ ████║██║ ██╔╝      ╚══██╔══╝██╔═══██╗██╔═══██╗██║          ║
║ ██████╔╝██╔████╔██║█████╔╝          ██║   ██║   ██║██║   ██║██║          ║
║ ██╔═══╝ ██║╚██╔╝██║██╔═██╗          ██║   ██║   ██║██║   ██║██║          ║
║ ██║     ██║ ╚═╝ ██║██║  ██╗         ██║   ╚██████╔╝╚██████╔╝███████╗     ║
║ ╚═╝     ╚═╝     ╚═╝╚═╝  ╚═╝         ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝     ║
║                 PMK Toolbox - Tối ưu Windows                             ║
╚══════════════════════════════════════════════════════════════════════════╝
"@
    Write-Host $logo -ForegroundColor $HEADER_COLOR
}

# utils.ps1 core
function Reset-ConsoleStyle {
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = $TEXT_COLOR
    Clear-Host
}

function Show-SystemHeader {
    $os = Get-CimInstance Win32_OperatingSystem
    $cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
    $ram = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
    $build = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId

    Write-Host "==================================================================================" -ForegroundColor $BORDER_COLOR
    Write-Host "PMK TOOLBOX v3.3.2" -ForegroundColor $HEADER_COLOR
    Write-Host "User: $($env:USERNAME) | PC: $($env:COMPUTERNAME) | OS: $($os.Caption) Build $build" -ForegroundColor $TEXT_COLOR
    Write-Host "CPU: $($cpu.Name.Split('@')[0].Trim()) | RAM: $ram GB" -ForegroundColor $TEXT_COLOR
    Write-Host "Author: Minh Khải (PMK) - https://www.facebook.com/khaiitcntt" -ForegroundColor $HEADER_COLOR
    Write-Host "==================================================================================" -ForegroundColor $BORDER_COLOR
    Write-Host ""
}

# install-apps.ps1 (sample - bạn thay bằng code thật nếu cần)
function Install-AppsQuick {
    Write-Host "Chức năng cài app đang được phát triển..." -ForegroundColor $WARNING_COLOR
    Start-Sleep 2
}

# tweaks.ps1 (sample)
function Invoke-TweaksMenu {
    Write-Host "Chức năng tweaks đang được phát triển..." -ForegroundColor $WARNING_COLOR
    Start-Sleep 2
}

# dns-management.ps1 (sample)
function Set-DNSServerMenu {
    Write-Host "Chức năng DNS đang được phát triển..." -ForegroundColor $WARNING_COLOR
    Start-Sleep 2
}

# clean-system.ps1 (sample)
function Invoke-CleanSystem {
    Write-Host "Đang dọn dẹp tạm thời..." -ForegroundColor $SUCCESS_COLOR
    Remove-Item -Path "$env:TEMP\*" -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "Hoàn tất!" -ForegroundColor $SUCCESS_COLOR
    Start-Sleep 2
}

# ────────────────────────────────────────────────────────────────
# MENU CHÍNH
# ────────────────────────────────────────────────────────────────
do {
    Reset-ConsoleStyle
    Show-PMKLogo
    Show-SystemHeader

    Write-Host "MENU CHÍNH - PMK TOOLBOX (Bundled)" -ForegroundColor $HEADER_COLOR
    Write-Host "====================================" -ForegroundColor $BORDER_COLOR
    Write-Host ""

    Write-Host " [1] Cài đặt ứng dụng nhanh"          -ForegroundColor $HEADER_COLOR
    Write-Host " [2] Vô hiệu hóa Telemetry & Tweaks" -ForegroundColor $HEADER_COLOR
    Write-Host " [3] Dọn dẹp file tạm & hệ thống"    -ForegroundColor $HEADER_COLOR
    Write-Host " [4] Quản lý DNS & mạng"             -ForegroundColor $HEADER_COLOR
    Write-Host " [5] Thoát"                           -ForegroundColor $HEADER_COLOR

    Write-Host ""
    Write-Host "Nhập số (1-5) hoặc ESC để thoát: " -NoNewline -ForegroundColor $HEADER_COLOR

    $input = Read-Host

    if ([Console]::KeyAvailable) {
        $key = [Console]::ReadKey($true)
        if ($key.Key -eq [ConsoleKey]::Escape) {
            Write-Host "`nThoát chương trình..." -ForegroundColor $BORDER_COLOR
            exit
        }
    }

    switch ($input.Trim()) {
        "1" { Install-AppsQuick }
        "2" { Invoke-TweaksMenu }
        "3" { Invoke-CleanSystem }
        "4" { Set-DNSServerMenu }
        "5" { Write-Host "Tạm biệt! Cảm ơn đã sử dụng." -ForegroundColor $HEADER_COLOR; exit }
        default { Write-Host "Lựa chọn không hợp lệ!" -ForegroundColor $ERROR_COLOR; Start-Sleep 1 }
    }
} while ($true)